server:
  port: 8080


spring:
  datasource:
    url: jdbc:p6spy:h2:mem:userdev;INIT=CREATE SCHEMA IF NOT EXISTS userdev
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  jpa:
    hibernate:
      ddl-auto: update
  sleuth:
    sampler:
      probability: 100.0
  zipkin:
    baseUrl: http://127.0.0.1:9411/
#  application:
#    name: user

management:
  endpoints:
    web:
      exposure:
        include: health,info