---
micronaut:
    application:
        name: report

#Uncomment to set server port
    server:
        port: 8081

---
tracing:
  zipkin:
    enabled: true
    traceId128Bit: true
    http:
      url: http://localhost:9411
      sampler:
        probability: 1
