global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'zipkin'
    scrape_interval: 5s
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['zipkin:9411']
  - job_name: 'reports'
    scrape_interval: 5s
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['192.168.11.5:8081']
  - job_name: 'edge'
    scrape_interval: 5s
    metrics_path: '/admin/metrics'
    static_configs:
      - targets: ['192.168.11.5:5051']
  - job_name: 'hub'
    scrape_interval: 5s
    metrics_path: '/admin/metrics'
    static_configs:
      - targets: ['192.168.11.5:5050']
  - job_name: 'reports-custom'
    scrape_interval: 5s
    metrics_path: '/admin/prometheus'
    static_configs:
      - targets: ['192.168.11.5:8081']
